title: Updates from Michael Camilleri
tagline: I forget my keys occasionally.
description: I live in Tokyo. I'm from Sydney. I speak in declarative sentences. Sometimes.
timezone: Asia/Tokyo

author:
  name: Michael Camilleri
  site: inqk.net
  url: https://inqk.net
  avatar: "/assets/images/avatar.jpg"

permalink: "/post/:epoch.html"
relative_permalinks: false

max_posts: 20

markdown: "CommonMark"

commonmark:
  options: ["FOOTNOTES", "SMART", "UNSAFE"]

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

weeknotes:
  description: This is one of Michael's weekly update posts. You could read it. Nothing's stopping you.

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: frame
  - scope:
      path: ""
      type: posts
    values:
      title: ""
      layout: post
