title: "Michael Camilleri"
tagline: "I forget my keys occasionally."
description: "I live in Tokyo. I'm from Sydney. I speak in declarative sentences. Sometimes."

timezone: "Asia/Tokyo"

baseurl: ""
url: "https://updates.inqk.net"
permalink: "/post/:epoch.html"
relative_permalinks: false

max_posts: 20

markdown: "CommonMark"

commonmark:
  options: ["FOOTNOTES", "SMART", "UNSAFE"]
  extensions: []

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  sass_dir: assets/stylesheets
  style: :compressed

plugins: ["jekyll-paginate"]

author:
  name: "Michael Camilleri"
  url: "https://inqk.net/"
  email: "mike@inqk.net"
  avatar: "https://micro.blog/pyrmont/avatar.jpg"
  twitter: "pyrmont"

bio: "I live in Tokyo. I'm from Sydney. I speak in declarative sentences. Sometimes."

weeknotes:
  description: "This is one of Michael's weekly update posts. You could read it. Nothing's stopping you."

links:
  mastodon: "https://social.lol/@pyrmont"
  twitter: "https://twitter.com/pyrmont"
  github: "https://github.com/pyrmont"
  pgpkey: "https://inqk.net/7EB218A48DF8B572.asc"

podcast: false

itunes_description: "I live in Tokyo. I'm from Sydney. I speak in declarative sentences. Sometimes."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Michael Camilleri"
itunes_email: "mike@inqk.net"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      title: ""
      layout: post
