source "https://rubygems.org"

gem "jekyll"

group :posteriser_gems do
  gem "gammo"
  gem "racc"
end

group :jekyll_deps do
  gem "base64"
  gem "bigdecimal"
  gem "csv"
end

group :jekyll_plugins do
  gem "commonmarker-pluggable", github: "pyrmont/commonmarker-pluggable", branch: "master"
  gem "jekyll-commonmark"
  gem "jekyll-github-metadata"
  gem "jekyll-paginate"
end

group :development do
  gem "webrick"
end
